CREATE TABLE IF NOT EXISTS `#__ffmedia` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `media_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `folder_path` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `extension` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `date_trashed` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `date_deleted` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `width` int(11) NOT NULL DEFAULT '0',
  `height` int(11) NOT NULL DEFAULT '0',
  `size` int(11) NOT NULL DEFAULT '0',
  `tn_width` int(11) NOT NULL DEFAULT '0',
  `alt` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `caption` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hash` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` tinyint(3) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `folder_path` (`folder_path`),
  KEY `file_name` (`file_name`),
  KEY `state` (`state`),
  KEY `media_type` (`media_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;